apiVersion: v1
kind: Secret
metadata:
  name: common-settings
data:
  domainSuffix: BASE64_DOMAIN_SUFFIX
---
apiVersion: v1
data:
  password: BASE64_GIT_API_KEY_OR_PASSWORD
  username: BASE64_GIT_USER_NAME
kind: Secret
metadata:
  annotations:
    tekton.dev/git-0: https://github.com
  labels:
    serviceAccount: pipeline
  name: git-secret
type: kubernetes.io/basic-auth