apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: dp-demo
  name: el-dp-demo
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-dp-demo
