apiVersion: v1
kind: ServiceAccount
metadata:
  name: dp-demo
  namespace: cp4i-datapower
secrets:
- name: git-secret
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dp-demo
rules:
# Permissions for every EventListener deployment to function
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Permissions to create resources in associated TriggerTemplates
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns"]
  verbs: ["create"]
- apiGroups: ["datapower.ibm.com"]
  resources: ["datapowerservices"]
  verbs:  ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dp-demo
subjects:
- kind: ServiceAccount
  name: dp-demo
  namespace: cp4i-datapower
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dp-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dp-demo-edit
subjects:
- kind: ServiceAccount
  name: dp-demo
  namespace: cp4i-datapower
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
