apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: install-datapower
spec:
  inputs:
    resources:
    - name: source
      type: git
    params:
    - name: env
      default: "dev"
      description: Specfiy the current environment. The value is used in computing the DataPowerService name.
    - name: production
      default: "false"
      description: Specifies if the deployment is production-like with High Availability enabled. Default [false]
    - name: dpconfig
      description: Specify the DataPower configuration to be used for installing the service.
      default: dp-demo
            
  steps:
  - name: install-instance
    image: docker.io/rsundara/cp4i-setup
    workingdir: /workspace/source
    env:
      - name: DOMAIN_SUFFIX
        valueFrom:
          secretKeyRef:
            name: common-settings
            key: domainSuffix    
      - name: PRODUCTION
        value: $(inputs.params.production) 
      - name: DATAPOWER_CONFIG
        value: $(inputs.params.dpconfig) 
      - name: ENV
        value: $(inputs.params.env) 
      - name: SERVICE_NAME
        value: $(inputs.params.dpconfig)-$(inputs.params.env)         
        
    command: ["/bin/sh"]
    args:
      - -c
      - |
        set -eu;
        echo DataPower Config : $DATAPOWER_CONFIG;
        echo Servic Name      : $SERVICE_NAME;
        echo Production       : $PRODUCTION;
        echo Domain suffix    : $DOMAIN_SUFFIX;
        
        cd ./datapower-services/$DATAPOWER_CONFIG/scripts
        
        echo "Running install.sh";
        sh install.sh;
                